### ISSUE TITLE
Implementing Data Access Layer

### ISSUE THREAD

**Issue by Benoh** [CourseMates/CourseMates#4]
#### Estimation
- [ ] 1 Day
- [ ] 2 Day
- [x] 3 Day+
#### Subtasks
- [ ] Implement SQL stored procedures.
- [ ] Write SQL queries.
- [x] Implement the C# DataAccess class.
- [x] Implement the C# project object class.
- [ ] Implement the CourseMate DAL class.
- [ ] Reveal Web service interface.
  @gissues:{"order":75,"status":"inprogress"}
