### ISSUE TITLE
Main features end to end development

### ISSUE THREAD

**Issue by Benoh** [CourseMates/CourseMates#6]
#### Estimation
- [ ] 1 Day
- [x] 2 Day
- [ ] 3 Day+
#### Subtasks
- [ ] Identify main features in our project.
- [ ] Develop the features end to end.
- [ ] Testing from bottom to top. 
  @gissues:{"order":93.75,"status":"done"}
